[package]
name = "simple-file-compressor"
version = "0.1.0"
edition = "2024"

[dependencies]
docopt = "1.1.1"
num-bigint = "0.4.6"
num_cpus = "1.16.0"
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive"] }
